name: directory-listing
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: .      #directory to generate index

      - name: Upload docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          clean: false
          force: true
