name: directory listing
on:
  workflow_dispatch:

jobs:
  auto-index:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    env:
      CI_COMMIT_MESSAGE: Benchmarks
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Benchmarks
      CI_COMMIT_EMAIL: $GITHUB_TRIGGERING_ACTOR@users.noreply.github.com
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Auto Index
        run: |-
          git checkout main -- .github/scripts/auto-index.sh
          .github/scripts/auto-index.sh .
          git status

      - name: Commit directory index
        run: |-
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git status
          git checkout main -- .github/scripts/auto-index.sh
          git add index.html
          git add docs
          git commit --allow-empty -m "Directory listing indexes"
          git push origin gh-pages:gh-pages

