name: auto-index
on:
  workflow_dispatch:
    
permissions:
  actions: write

jobs:
  auto-index:
    runs-on: ubuntu-latest
    steps:
      - name: Get auto-index-script
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Auto Index
        run: gh workflow run auto-index.yml -r $(git rev-parse --abbrev-ref HEAD)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

